### PR TITLE
Upgrade to laravel 6.0

### PR DESCRIPTION
**Pull request by v8-ict**
Please add these, to allow people to upgrade to laravel 6.0

### CODE REVIEW

**Comment by JanWeskamp** [comment]
Please <3

**Comment by vaanholtje** [comment]
The package from Blue Dragon Laravel Routes: https://packagist.org/packages/bluedragon/laravel-routes supports Laravel 6. 

They have created also  a section in the readme how to migrate from lord/laroute. 
https://gitlab.com/blue-dragon/laravel-routes#migrating-from-lordlaroute

**Comment by v8-ict** [comment]
I migrated to Blue Dragon as well, it was pretty painless migration, and the support / adoption from Blue Dragon is SuperB, however i did send in this PR anyway for if, someone wake's up another day.

Such i minor fix, can help many.

**Comment by sergiz** [comment]
I suppose that the more "appropriate" way to specify Laravel requirements now would be:
`"^5.0|^6.0",`

L5 branch is complete anyway, and L6 follows simver anyway.

**Comment by Kovalchuk91** [comment]
@aaronlord Can you please update what's the status of this repo. Waiting for 6.* support also

**Comment by frekel** [comment]
@aaronlord Can you please update and merge this MR?

**Pull request merged**
