### PR TITLE
Laravel 5.8

### PR DESCRIPTION
**Pull request by dallincoons**
Upgrade to Laravel 5.8 and replace deprecated global helper.

### CODE REVIEW

**Comment by marcodevsquad** [comment]
What should be done to this PR be accepted @aaronlord ?

**Comment by nexxai** [comment]
@aaronlord Any chance you could just accept this PR so we can move to Laravel 5.8?

**Comment by marcodevsquad** [comment]
I found a better package that you don’t need to generate a JavaScript file if you want. It’s called ziggy. https://github.com/tightenco/ziggy

**Comment by ggportfoliowork** [comment]
Submitted for your approval...of the midnight society...I dub this PR...THE TALE OF DEAD LARAVEL PACKAGES

**Comment by dallincoons** [comment]
If anyone is interested, I created a fork that updates the version of Laravel to 5.8. I'm not going to be maintaining it other than that, but it should buy you some time before switching to Ziggy. https://github.com/surgiollc/laroute

**Comment by tvbeek** [comment]
My colleagues from Blue Dragon and I released a new Laravel package called Laravel Routes. https://packagist.org/packages/bluedragon/laravel-routes
In this post I would like to explain about the "why" and "hows" we created this package: https://tjvb.nl/post/laravel-routes

We created a section in the readme how to migrate from lord/laroute. We want that to be easy because we have to migrate our own projects 😃 
https://gitlab.com/blue-dragon/laravel-routes#migrating-from-lordlaroute

**Pull request merged**
